### ISSUE TITLE
Spawnpositionen

### ISSUE THREAD

**Issue by Kabumba** [PG642/RoboLeague#17]

**Comment by hndm** [comment]
Do not implement spawn positions as a controller but as game objects. Have to be added to the RocketMap Prefab.

**Comment by bsati** [comment]
GetSpawnPosition has an index error when used because the index increments when the spawn is on cooldown and can run out of bounds. See https://github.com/PG642/RoboLeague/commit/0243d66644a7590c1ecf57aca6a2b645437e80b7#r51994510
