### ISSUE TITLE
Auto-Auto Interaktion

### ISSUE THREAD

**Issue by TheImus** [PG642/RoboLeague#61]

**Comment by JaDr47** [comment]
1. Das gerammte Fahrzeug fliegt nicht hoch genug (s. bumped_car_y_location.png). Das Verhältnis beim Bullet-Impuls von x- zu y-Koordinate scheint nicht zu stimmen.
Idee: Kontaktpunkt zur Berechnung des Bullet-Impulses müsste in diesem Szenario angepasst werden. Wie man das allgemeingültig machen kann ist uns derzeit noch ein Rätsel. Möglicher Ansatz: Berechnung in Abhängigkeit des Masseschwerpunktes anstatt des Mittels aller durch Unity registrierten Kontaktpunkte (Masseschwerpunkt liegt etwas niedriger)
2. Das gerammte Fahrzeug dreht sich zu stark ein (s. bumped_car_roll.png). Problem ist hier der Punkt, an dem der Impuls angewendet wird. Nimmt man den gemittelten Kollisionspunkt ist die Rotation zu stark, genauso wie bei dem Masseschwerpunkt. Nimmt man die Position des Rigidbodys hat man keine Rotation. Bei der Untersuchung der Rotation ist aufgefallen, dass der in den Bildern zu sehende Verlauf der y-location durch die Rotation geprägt ist. Durch das starke eindrehen entsteht eine Hebelwirkung, die das Auto vom Boden abheben lässt.
3. Der Impuls, der auf das gerammte Auto ausgewirkt werden müsste scheint höher zu sein, als der einfache Bullet-Impuls. Hier könnte zusätzlich der Psyonix-Impuls greifen. Dokumentation darüber haben wir nicht gefunden. Mit dem Psyonix-Impuls konnten wir die Ergebnisse aus den Bildern erzeugen. Zuerst hatten wir die Vermutung, dass der Psyonix-Impuls das erste Problem lösen könnte. Dieser Impuls überträgt jedoch nahezu keine Energie in y-Richtung.

Der Zusammenhang zwischen den Problemen macht es schwierig sich den Problemen einzelnen zu widmen. Will man den Psyonix-Impuls zusätzlich anwenden stellen sich hier die gleichen Fragen bei der Berechnung des Kontakt- und und Anwendungspunktes des Impulses
![bumped_car_x_location](https://user-images.githubusercontent.com/82369838/144233805-430eca6f-6251-438b-8c90-a370943710e5.png)
![bumped_car_roll](https://user-images.githubusercontent.com/82369838/144233809-46e6c0c6-ab13-44c2-a3c5-e825cd04d4a8.png)
![bumped_car_y_location](https://user-images.githubusercontent.com/82369838/144233812-65731b56-72e0-4a69-95b6-f1cc7d4591aa.png)
.
