### ISSUE TITLE
Multi Agent Umgebung für verteilte Lernen

### ISSUE THREAD

**Issue by TheImus** [PG642/RoboLeague#90]

**Comment by lonmon** [comment]
Ich habe schon eine 1v1 Umgebung mit dem dazugehörigen Agenten in unserem RoboLeague Projekt gebaut. Die Umgebung könnt ihr im Projekt unter Assets > ML-Agents > 1v1 finden und dann ein Build von der Umgebung machen.

Hendrik und ich haben heute auch unseren gym wrapper auf einer ppo Implementierung getestet, was gut funktioniert hat. Ihr könnt den wrapper also auch gerne benutzen.
